import * as t from '../types';

const initialState = {
    filtro: {
        per_page: 25,
        rangoABV: [0, 60],
        listaLevaduras: [],
        listaLupulos: [],
        listaMaltas: [],
        listaComidas: []
    },
    listaCervezas: [],
    listaCervezasAux: [],
    //Listas estáticas para filtros
    listaLevaduras: [
        { name: "Saflager S189", color: "#b9945e" },
        { name: "WLP099 - Super High Gravity Ale", color: "#b95e5e" },
        { name: "WLP500 - Monastery Ale", color: "#b8b95e" },
        { name: "Wyeast 1010 - American Wheat™", color: "#5eb993" },
        { name: "Wyeast 1056 - American Ale™", color: "#5e87b9" },
        { name: "Wyeast 1272 - American Ale II™", color: "#895eb9" },
        { name: "Wyeast 2007 - Pilsen Lager™", color: "#b95e84" },
        { name: "Wyeast 3333 - German Wheat™", color: "#5e97b9" },
        { name: "Wyeast 3522 - Belgian Ardennes™", color: "#7db95e" },
        { name: "Wyeast 3638 - Bavarian Wheat™", color: "#4e5e8d" },
        { name: "Wyeast 3711 - French Saison™", color: "#8d514e" },
        { name: "Wyeast 3787 - Trappist High Gravity™", color: "#8d4e88" }
    ],
    listaLupulos: [
        "Ahtanum",
        "Amarillo",
        "Blackberry Concentrate",
        "Bobek",
        "Bramling Cross",
        "CO2 Extract",
        "Cascade",
        "Centennial",
        "Challenger",
        "Chinook",
        "Citra",
        "Coffee",
        "Coffee Beans",
        "Columbus",
        "Columbus Extract",
        "Crystal",
        "Dana",
        "First Gold",
        "Fuggles",
        "Galena",
        "Ginger",
        "Goldings",
        "HBC 369",
        "Hallertauer Mittelfrüh",
        "Hersbrucker",
        "Honey",
        "Hop Extract",
        "Kohatu",
        "Lactose",
        "Magnum",
        "Mandarina Bavaria",
        "Mosaic",
        "Motueka",
        "Mt.Hood",
        "Nelson Sauvin",
        "Orange Peel",
        "Pacific Jade",
        "Pacifica",
        "Peppercorns",
        "Saaz",
        "Simcoe",
        "Sorachi Ace",
        "Sour Cherry Puree",
        "Tomahawk",
        "Vic Secret",
        "Waimea",
        "Willamette"
    ],
    listaMaltas: [
        "Acidulated Malt",
        "Acidulated Malt for kettle souring",
        "Amber",
        "Black Malt",
        "Black Patent",
        "Brown",
        "Carafa Special Malt Type 1",
        "Carafa Special Malt Type 3",
        "Caramalt",
        "Chocolate",
        "Crystal",
        "Crystal 120",
        "Crystal 150",
        "Dark Crystal",
        "Dark Crystal 350",
        "Dark Crystal 350-400",
        "Dextrose",
        "Extra Pale",
        "Extra Pale - Spring Blend",
        "Flaked Oats",
        "Honey",
        "Lager Malt",
        "Maris Otter Extra Pale",
        "Munich",
        "Pale Ale",
        "Pale Ale - Tipple",
        "Pale Chocolate",
        "Pale Crystal",
        "Peated Malt",
        "Popcorn",
        "Propino Pale Malt",
        "Propino Pale Malt for kettle souring",
        "Roasted Barley",
        "Rye",
        "Smoked Malt",
        "Smoked Peaty",
        "Smoked Weyermann",
        "Special W",
        "Torrified Wheat",
        "Weyermann Beech Smoked",
        "Wheat",
        "Wheat Malt"
    ],
    listaComidas: [
        "12hr smoked brisket",
        "20hr smoked brisket",
        "Almond biscotti",
        "Ancho chilli beef taco",
        "Andhra chicken pickle curry",
        "Angelfood cake",
        "Apple and blackcurrant cobbler",
        "Apple and rosemary tart",
        "Apple upside-down cake",
        "Apricot coconut cake",
        "Aromatic korma curry with lemon and garlic naan",
        "Arrabiata pasta",
        "Bacon sandwich with brown sauce",
        "Banana split",
        "Banana walnut loaf with chocolate chips",
        "Banoffee pie",
        "Barbecue corn and steak fajita seasoned wrap",
        "Barbecue pulled pork on sourdough bread",
        "Basil, lemon and pine nut angel hair pasta with grilled chicken",
        "Beef Stroganoff",
        "Beef Wellington with a red wine jus",
        "Beef chilli made with cocoa powder",
        "Beef mahaca on corn tortillas",
        "Beef satay skewers",
        "Beef, oyster and ale pie",
        "Blackberry mocha gateaux",
        "Blackened Cajun chicken",
        "Blackened cajun beef",
        "Blondies with chocolate fudge sauce",
        "Blue cheese",
        "Blue cheese & onion tart",
        "Blue cheese beef burger",
        "Blueberry pie",
        "Braised pheasant",
        "Bratwurst sausage with spicy mustard",
        "Butterscotch tart",
        "Candied almond and blue cheese rocket salad",
        "Candied bacon topped chocolate cheesecake",
        "Caramel and banana meringue pie",
        "Caramel and rose essence cheesecake",
        "Caramel sauce and hot fudge",
        "Caramel toffee cake",
        "Caramelised onion venison burger",
        "Caramelised scallops with burnt apple puree",
        "Carrot cake",
        "Chargrilled corn on the cob with paprika butter",
        "Cheesecake with raspberry coulis",
        "Chicago style hot links",
        "Chicken Tikka Madras",
        "Chicken fried steak with cheesy mash",
        "Chicken sausages with creamy mash",
        "Chilli and dark chocolate tart",
        "Chilli covered burger (Sloppy Joe)",
        "Chocolate and fruit cake",
        "Chocolate cake",
        "Chocolate caramel drizzled sponge cake",
        "Chocolate fudge ice cream",
        "Chocolate gateaux",
        "Chocolate milk shake",
        "Chocolate orange brownies",
        "Chocolate pistachio cakes",
        "Cinnamon & white chocolate churro",
        "Citrus salad with balsamic dressing",
        "Clootie dumpling",
        "Coffee dusted venison loin",
        "Coriander & chilli crab cakes",
        "Crab linguine",
        "Crab melt sandwich",
        "Cranachan",
        "Creamy chocolate and caramel cheesecake",
        "Creamy gorgonzola and satsuma salad",
        "Creamy lemon bar doused in powdered sugar",
        "Crispy bacon on flat bread",
        "Dark Chocolate Fondant",
        "Dark chocolate chip cookies",
        "Dark chocolate covered bacon",
        "Dark chocolate truffles",
        "Duck liver paté",
        "Dulche de leche",
        "Earthy mushroom pasta",
        "Epoisses cheese",
        "Fårikål (mutton stew) with a spicy twist",
        "Fenalår (salted cured lamb)",
        "Fish and chips",
        "Fish corn tacos with pomegranate salsa",
        "Fish tacos with hot sauce",
        "Flourless chocolate cheesecake",
        "French onion soup",
        "Fresh berry crisp tart",
        "Fresh crab with lemon",
        "Fresh pico de gallo with corn tortilla",
        "Fried American bacon with chilli flakes added to the top",
        "Fried crab cakes with avocado salsa",
        "Fried halibut with sweet potato fritters",
        "Garlic butter dipping sauce",
        "Ginger and orange cookies",
        "Ginger bread cookies",
        "Glazed ham with crackling coating",
        "Glazed short ribs",
        "Goan goat curry",
        "Goats cheese salad",
        "Goats cheese salad with walnuts, radish and blood orange",
        "Gooey chocolate brownies",
        "Gorgonzola and rye nut bread with smoked honey ham",
        "Gouda cheese",
        "Grapefruit and blood orange tart",
        "Grilled chicken quesadilla",
        "Grilled chicken salad with bacon and avocado",
        "Grilled fish salad",
        "Grilled portabello mushroom burger",
        "Grilled salmon",
        "Grilled salmon with a herb and citrus infused butter",
        "Grilled spicy corn with feta crumbles",
        "Grilled vegetable and chicken teriyaki skewers",
        "Haggis bon bons",
        "Halibut with a mango and tomato salad",
        "Halibut with caper brown butter",
        "Hazelnut brittle",
        "Hickory smoked ham",
        "Honey glazed ham",
        "Kedgeree",
        "Key Lime Pie",
        "Key lime pie",
        "King prawn kebabs",
        "Kippers and poached eggs",
        "Kirsch chocolate truffles",
        "Korean style chicken wings",
        "Krumkake with lingonberry jam",
        "Lamb chops with caramelised figs",
        "Lapin aux pruneaux (braised rabbit with prunes)",
        "Lavender and thyme roast beef",
        "Lavender chocolate chip cookies",
        "Lemon poppyseed donuts",
        "Lemon pound cake with a ice sugar glaze",
        "Lobster",
        "Mac and cheese fries",
        "Margherita pizza",
        "Matcha green tea cake",
        "Mature cheddar with red onion chutney",
        "Memphis-style beef short ribs",
        "Millionaire's shortbread",
        "Mint chocloate ice cream",
        "Miso ramen",
        "Monterey Jack stuffed grilled jalepenos",
        "Mozzarella and tomato baked chicken",
        "Mulled cheddar",
        "Mussels with a garlic and herb sauce",
        "Mutton stew",
        "Oatmeal and cranberry cookies",
        "Orange tart",
        "Oysters",
        "Pad Thai",
        "Pan seared scallops with a chilli sauce",
        "Pan seared steak",
        "Pan seared venison fillet with juniper sauce",
        "Pastrami",
        "Peanut brittle",
        "Pecan pie",
        "Pineapple upside down cake",
        "Pistachio cake",
        "Poached eggs and smoked salmon",
        "Poached pear",
        "Poached sole fillet with capers",
        "Popcorn caramel and chocolate cake",
        "Pork belly vindaloo",
        "Pot roasted artichokes",
        "Potted fresh & smoked salmon",
        "Pulled pork",
        "Quince cheese",
        "Raspberry chocolate torte",
        "Raspberry coffee cheesecake",
        "Red pepper houmous and flat bread",
        "Rhubarb pie",
        "Rich espresso tiramisu",
        "Roast beef",
        "Roast beef with spicy jus",
        "Roast chicken with vegetables and wild rice",
        "Roast turkey with a honey and herb marinade and roasted vegetables",
        "Roasted butternut squash",
        "Roasted duck",
        "Roasted garlic and chilli infused camembert cheese",
        "Roasted wood pigeon with black pudding",
        "Rocket and mozzarella salad with a cracked pepper dressing",
        "Rocky Road",
        "Rosemary and lemon roast chicken",
        "Rosemary and thyme marinated venison",
        "Rum poached pears with dark chocolate sauce",
        "Russian mini pork pies",
        "Salt and pepper squid",
        "Salt baked cod with lemon and dill butter",
        "Sashimi",
        "Scotch broth with sourdough bread",
        "Seared lemon and herb salmon",
        "Sharp cheddar cheese and onion/ raisin chutney",
        "Shortbread cookies",
        "Shredded chicken and mango salsa taquitos",
        "Slow cooked lamb shoulder with mint sauce",
        "Smoked chicken wings",
        "Smokey chipotle beef brisket tostada",
        "Spiced and blackened cajun chicken",
        "Spiced nut loaf",
        "Spiced shrimp salad",
        "Spicy Asian-style noodles",
        "Spicy Daal with garlic naan bread",
        "Spicy chicken empanadas",
        "Spicy chicken skewers",
        "Spicy chicken tikka masala",
        "Spicy crab cakes",
        "Spicy cucumber and carrot Thai salad",
        "Spicy jalapeño & seared steak fajitas",
        "Spicy kung po chicken",
        "Spicy shredded pork roll with hot dipping sauce",
        "Spicy wings with blue cheese dip",
        "Stilton",
        "Stilton on gingerbread biscuits",
        "Strawberry and citrus salad",
        "Strawberry and rhubarb pie",
        "Strawberry cheescake",
        "Strong blue cheese",
        "Sugar-poached kumquat rice pudding",
        "Summer berry fruit parfait",
        "Summer fruit salad",
        "Sweet filled dumplings",
        "Sweet pork Chinese dumplings",
        "Sweet potato pie",
        "Swiss and horseradish sandwich",
        "Tandoori lamb with pomegranate",
        "Thai green curry",
        "Toasted almond cake",
        "Toffee marshmallow pie",
        "Tom yum soup",
        "Tuna sushi roll with spicy mayonnaise sauce",
        "Vegetable egg scramble",
        "Venison & cranberry pie",
        "Venison with cacao nibs",
        "Vietnamese squid salad",
        "Vinegar doused fish and chips",
        "Warm blackberry pie",
        "Yuzu cheesecake"
    ]
}

const main = (state = initialState, action: any) => {
    switch (action.type) {
        case t.SET_FILTRO:
            return {
                ...state,
                filtro: action.value
            };
        case t.SET_LISTA_CERVEZAS:
            return {
                ...state,
                listaCervezas: action.value
            };
        case t.SET_LISTA_CERVEZAS_AUX:
            return {
                ...state,
                listaCervezasAux: action.value
            };
        case t.RESET_FILTRO:
            return {
                ...state,
                filtro: initialState.filtro,
                listaCervezas: state.listaCervezasAux
            }
        default:
            return { ...state };
    }
}

export default main;