export const SET_FILTRO = "SET_FILTRO";
export const SET_LISTA_CERVEZAS = "SET_LISTA_CERVEZAS";
export const SET_LISTA_CERVEZAS_AUX = "SET_LISTA_CERVEZAS_AUX";
export const RESET_FILTRO = "RESET_FILTRO";
